---

- name: Setup server core
  hosts:
    - all
  user: ubuntu
  sudo: yes

  pre_tasks:
    - name: update apt if needed
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

  roles:
    - monitoring
    - security
    - tmux
    - utils

- name: Setup app core
  user: ubuntu
  sudo: yes
  hosts:
    - web
    - util
    - db
  roles:
    - ruby
    - gdal
    - memcached
    - app

- name: Setup web
  hosts:
    - web
  user: ubuntu
  sudo: yes

  roles:
    - nginx

- name: Setup web, util
  hosts:
    - web
    - util
  user: ubuntu
  sudo: yes

  roles:
    - postgresql-client

- name: Setup util
  hosts:
    - util
  user: ubuntu
  sudo: yes

  roles:
    - redis
    - sidekiq

- name: Setup db
  hosts:
    - db
  user: ubuntu
  sudo: yes

  roles:
    - postgresql-server

- name: Setup elastic search nodes
  hosts:
    - elasticsearch
  user: ubuntu
  sudo: yes

  roles:
    - elasticsearch
