---

- name: Setup server
  hosts:
    - staging
    - production
  user: ubuntu
  sudo: yes

  pre_tasks:
    - name: update apt if needed
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

  roles:
    - monitoring
    - security
    - nginx
    - tmux
    - utils
    - ruby
    - gdal
    - postgresql
    - redis
    - memcached
    - app
