language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install gdal-bin
  - sudo apt-get install libgdal1-dev
  - sudo apt-get install libgdal-dev
bundler_args: --without development production staging
rvm:
  - 2.1.2
before_script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate
notifications:
  email:
    - adam.mulligan@unep-wcmc.org
    - miguel.torres@unep-wcmc.org
branches:
  only:
    - master
