language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install gdal-bin
bundler_args: --without development production staging
rvm:
  - 2.1.2
notifications:
  email:
    - adam.mulligan@unep-wcmc.org
    - miguel.torres@unep-wcmc.org
branches:
  only:
    - master
addons:
  code_climate:
    repo_token:
      secure: "YsOamnH3K8SwysSe2EKm11Wi+Qi0ZsTMGDL3jD+9uWYWM6+MIFEFY7xJf2psoImHzzMoJE5EYtIbQBNk0WB2dtehdaI29yaQ+5RFoMw+z+M2t119GKE3QgD8W0vlhXWKadVXbSnU3EUCaHn+u2rzFU0jNx/+GCoPuG2ltfJf404="
