language: ruby
before_install:
  - sudo apt-add-repository --remove ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install gdal-bin
  - sudo apt-get install libgdal1-dev
  - sudo apt-get install libgdal-dev
  - sudo apt-get install Postgresql-9.3-postgis -f
  - psql -c 'create database pp_test' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d pp_test
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d pp_test
bundler_args: --without development production staging --jobs=6
rvm:
  - 2.1.2
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate
notifications:
  email:
    - andrea.rossi@unep-wcmc.org
branches:
  only:
    - master
    - fix-travis-build
addons:
  code_climate:
    repo_token:
      secure: "YsOamnH3K8SwysSe2EKm11Wi+Qi0ZsTMGDL3jD+9uWYWM6+MIFEFY7xJf2psoImHzzMoJE5EYtIbQBNk0WB2dtehdaI29yaQ+5RFoMw+z+M2t119GKE3QgD8W0vlhXWKadVXbSnU3EUCaHn+u2rzFU0jNx/+GCoPuG2ltfJf404="
  postgresql: 9.3

