language: ruby
before_install:
  - sudo apt-get purge postgis
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install gdal-bin
  - sudo apt-get install libgdal1-dev
  - sudo apt-get install libgdal-dev
  - sudo apt-get install postgresql-9.3-postgis-2.1 -f
  - psql -c 'create database pp_test' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d pp_test
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d pp_test
bundler_args: --without development production staging --jobs=4
rvm:
  - 2.1.2
before_script:
  - RAILS_ENV=test bundle exec rake db:migrate
notifications:
  email:
    - adam.mulligan@unep-wcmc.org
    - andrea.rossi@unep-wcmc.org
    - miguel.torres@unep-wcmc.org
branches:
  only:
    - master
addons:
  code_climate:
    repo_token:
      secure: "YsOamnH3K8SwysSe2EKm11Wi+Qi0ZsTMGDL3jD+9uWYWM6+MIFEFY7xJf2psoImHzzMoJE5EYtIbQBNk0WB2dtehdaI29yaQ+5RFoMw+z+M2t119GKE3QgD8W0vlhXWKadVXbSnU3EUCaHn+u2rzFU0jNx/+GCoPuG2ltfJf404="
  postgresql: 9.3

