---
- name: Checking installed version of GDAL
  shell: /usr/bin/test $(ogrinfo --version |  sed -n 's/GDAL \(.*\), released.*/\1/p') = {{gdal.version}}
  register: gdal_installed
  ignore_errors: True

- name: Install gdal dependencies
  apt: pkg=$item state=installed update-cache=yes
  when: gdal_installed.rc != 0
  with_items:
    - build-essential
    - python-all-dev

- name: Download gdal
  when: gdal_installed.rc != 0
  get_url: url={{gdal.url}} dest=/tmp/gdal-{{ gdal.version }}.tar.gz

- name: Extract gdal
  when: gdal_installed.rc != 0
  command: tar -xvf /tmp/gdal-{{ gdal.version }}.tar.gz -C /tmp/gdal-{{ gdal.version }} chdir=/tmp
  sudo: yes

- name: Make, configure, and install gdal
  when: gdal_installed.rc != 0
  command: chdir=/tmp/gdal-{{ gdal.version }} {{item}}
  with_items:
    - ./configure --with-python
    - make
    - sudo make install
