---

- name: Install GEOS
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - libgeos-dev
    - libgeos-{{ geos.version }}

- name: Symlink libgeos to correct place for use by RGeo
  file: src=/usr/lib/libgeos-{{geos.version}}.so dest=/usr/lib/libgeos.so state=link
  sudo: yes

- name: Add UbuntuGIS Unstable repository
  apt_repository: repo='{{ gdal.repo }}' state=present

- name: Checking installed version of GDAL
  shell: /usr/bin/test $(ogrinfo --version |  sed -n 's/GDAL \(.*\), released.*/\1/p') = {{gdal.version}}
  register: gdal_installed
  ignore_errors: True

- name: Add repository key
  apt_key: data="{{ lookup('file', '314DF160.asc') }}"  state=present
  when: gdal_installed.rc != 0

- name: Install gdal dependencies
  apt: pkg=$item state=installed update-cache=yes
  when: gdal_installed.rc != 0
  with_items:
    - build-essential
    - python-all-dev
    - libgdal1h

- name: Download gdal
  when: gdal_installed.rc != 0
  get_url: url={{gdal.url}} dest=/tmp/gdal-{{ gdal.version }}.tar.gz

- name: Make directory for gdal tarball
  file: path=/tmp/gdal-{{ gdal.version }} state=directory

- name: Extract gdal
  when: gdal_installed.rc != 0
  command: tar -xvf /tmp/gdal-{{ gdal.version }}.tar.gz -C /tmp/gdal-{{ gdal.version }} --strip-components 1
  sudo: yes

- name: Make, configure, and install gdal
  when: gdal_installed.rc != 0
  command: chdir=/tmp/gdal-{{ gdal.version }} {{item}}
  with_items:
    - ./configure --with-python
    - make
    - sudo make install
