- name: Add postgres repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

- name: Add Key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
 
- name: Install PGTune
  apt: name=pgtune state=installed update_cache=true

- name: Ensure apt is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{item}}
  with_items:
      - postgresql-9.4
      - postgresql-9.4-postgis-2.1
      - postgresql-contrib-9.4
      - libpq-dev  
         
- name: Back up postgres config file
  command: mv /etc/postgresql/9.4/main/postgresql.conf /etc/postgresql/9.4/main/postgresql.conf.old


- name: Setting Postgresql Optmizing via pgtune
  command: pgtune
            -i /etc/postgresql/9.4/main/postgresql.conf.old
            -o /etc/postgresql/9.4/main/postgresql.conf
  
- name: Change owner of postgres config file to postgres
  file: path=/etc/postgresql/9.4/main/postgresql.conf owner=postgres group=postgres mode=0644

