---

- name: Install app nginx config
  template: src=app.nginx.j2 dest=/etc/nginx/sites-available/default
  sudo: yes
  notify:
    - restart nginx

- name: Install unicorn gem for Rails servers
  gem: name=unicorn state=present

- name: Install unicorn sysv config
  template: src=unicorn.j2 dest=/etc/init.d/unicorn mode=755
  sudo: yes
  notify:
    - "Start Unicorn"
