---
- name: Checking installed version of ruby
  shell: /usr/bin/test "$(ruby -e "puts RUBY_VERSION")" = {{ruby_version}}
  register: ruby_version_installed
  ignore_errors: True

- name: Install ruby dependencies
  apt: pkg=$item state=installed update-cache=yes
  when: ruby_version_installed.rc == 1
  with_items:
    - build-essential
    - libssl-dev
    - libreadline6-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libgdbm-dev
    - libncurses5-dev
    - libtool
    - bison
    - libffi-dev
    - libdigest-hmac-perl
    - unzip
    - zlib1g
    - zlib1g-dev
    - libpq-dev

- name: Download ruby
  when: ruby_version_installed.rc == 1
  get_url: url={{ruby_url}} dest=/tmp/ruby-{{ ruby_version }}.tar.gz

- name: Extract ruby
  when: ruby_version_installed.rc == 1
  command: tar -xvf /tmp/ruby-{{ ruby_version }}.tar.gz -C /tmp/ruby-{{ ruby_version }} chdir=/tmp
  sudo: yes

- name: Make, configure, and install ruby
  when: ruby_version_installed.rc == 1
  command: chdir=/tmp/ruby-{{ ruby_version }} {{item}}
  with_items:
    - ./configure
    - make
    - sudo make install

- name: Install bundler
  gem: name=bundler state=present
  sudo: yes
