aggregations:
  type_of_territory:
    type: "boolean"
    query: "marine"
    labels:
      T: "Marine"
      F: "Terrestrial"
    identifiers:
      T: true
      F: false
  related_sources:
    type: "grouped"
    members:
      has_parcc_info:
        type: "boolean"
        query: "has_parcc_info"
        labels:
          T: "Vulnerability Assessment"
        identifiers:
          T: true
      has_irreplaceability_info:
        type: "boolean"
        query: "has_irreplaceability_info"
        labels:
          T: "Irreplaceability Assessment"
        identifiers:
          T: true
  country:
    type: "model"
    class: "Country"
  region:
    type: "model"
    class: "Region"
  designation:
    type: "model"
    class: "Designation"
  iucn_category:
    type: "model"
    class: "IucnCategory"

filters:
    type:
      type: 'type'
    marine:
      type: 'equality'
      path: 'marine'
    iucn_category:
      type: 'nested'
      path: 'iucn_category'
      field: 'iucn_category.id'
      required: true
    designation:
      type: 'nested'
      path: 'designation'
      field: 'designation.id'
      required: true
    location:
      type: 'geo'
      path: 'location'
      field: 'protected_area.coordinates'
    has_parcc_info:
      type: 'equality'
      path: 'has_parcc_info'
    has_irreplaceability_info:
      type: 'equality'
      path: 'has_irreplaceability_info'
    country:
      type: 'nested'
      path: 'countries_for_index'
      field: 'countries_for_index.id'
      required: true
    region:
      type: 'nested'
      path: 'countries_for_index.region_for_index'
      field: 'countries_for_index.region_for_index.id'
      required: true
