# Be sure to restart your server when you modify this file.
default: &default
  host: <%= ENV['PP_HOST'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  maintenance_mode_key: <%= ENV['MAINTENANCE_MODE_KEY'] %>

  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_downloads_bucket: 'pp-downloads-development'
  aws_bucket: 'pp-import-development'
  aws_datasets_bucket: 'ppe.datasets'

  cartodb_api_key: <%= ENV["CARTODB_API_KEY"] %>
  cartodb_username: 'carbon-tool'

  raygun_api_key: <%= ENV["RAYGUN_API_KEY"] || "" %>
  new_relic_key: <%= ENV["NEW_RELIC_KEY"] %>

  wikipedia_api_url: 'http://en.wikipedia.org/w/api.php'

  default_map_bounds:
    from: [57.862288, -139.21875]
    to:   [-9.156333, 105.46875]

  redis:
    wdpa_imports_prefix: 'wdpa_imports'

  elasticsearch:
    url: 'http://localhost:9200'
    index: 'protected_areas'
    indexing:
      concurrency_level: 2
      batch_size: 1000

development:
  <<: *default
  secret_key_base: c9a5d44fd83941bdf5224c7ddd6da04361df0383bc45cc2e074c2b7ecc47f6730c1b5f53bd627d30182997fed6b80433c9e8040dc7f15d1bac6cbfa0a38c1dfa

test:
  <<: *default
  secret_key_base: 0f7fb46879c71772aafa694a4bdc5c821c196ab7b0b337ecf3fe994616ca2a243d4743cbfd984bb8033708c57b66cf97b5f999f11a19b8d42e72a956a7c1b770
  aws_access_key_id: ''
  aws_secret_access_key: ''
  cartodb_api_key: ''
  maintenance_mode_key: 'ankey'

#====================
# Production Secrets
#====================

production_defaults: &production_defaults
  <<: *default
  cache_max_age: '2592000'
  memcache_servers:
    - 'localhost:11211'

# Do not keep staging secrets in the repository,
# instead read values from the environment.
staging:
  <<: *production_defaults
  aws_downloads_bucket: 'pp-downloads-staging'
  aws_bucket: 'pp-import-staging'

  elasticsearch:
    url: 'http://10.146.199.43:9200'
    index: 'protected_areas'
    indexing:
      concurrency_level: 2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *production_defaults
  aws_downloads_bucket: 'pp-downloads-production'
  aws_bucket: 'pp-import-production'

  elasticsearch:
    url: '10.85.14.161'
    index: 'protected_areas'
    indexing:
      concurrency_level: 4
