---

- name: create a deploy user
  user: name=deploy
        state=present
- name: Create the SSH directory.
  file: state=directory path=/home/deploy/.ssh/
- name: Copy SSH Public Key
  command: cp /root/.ssh/authorized_keys /home/deploy/.ssh/authorized_keys
- name: Fix SSH public key permissions
  file: path=/home/deploy/.ssh/authorized_keys owner=deploy group=deploy
- name: Create permissions for /var/www
  file: path=/var/www state=directory owner=deploy group=deploy
