---

- name: Install git
  apt: name=git
  sudo: yes

- name: Copy global git config
  template: src=gitconfig.j2 dest=~/.gitconfig
- name: Copy global gitignore
  template: src=gitignore.j2 dest=~/.gitignore
