---

- name: Install iftop
  apt: name=iftop
  sudo: yes

- name: Install glances
  pip: name=glances
  sudo: yes

- name: Install htop
  apt: name=htop
  sudo: yes

- name: Install logwatch
  apt: name=logwatch
  sudo: yes
- name: Copy logwatch config
  template: src=logwatch.conf.j2 dest=/usr/share/logwatch/default.conf/logwatch.conf
  sudo: yes

- name: Install Munin
  apt: name=munin
  sudo: yes
- name: Install Munin nginx config
  template: src=munin.nginx.j2 dest=/etc/nginx/sites-available/munin
  sudo: yes
- name: Enable munin nginx config
  file: src=/etc/nginx/sites-available/munin dest=/etc/nginx/sites-enabled/munin state=link
  sudo: yes
  notify:
    - restart nginx

- name: Install Monit
  apt: pkg=monit state=installed update-cache=yes
  sudo: yes
  notify:
    - start monit

- name: Install Monit config
  template: src=monitrc-{{item}}.j2 dest=/etc/monit/monitrc mode=0700
  with_items: group_names
  notify:
    - reload monit
